### ISSUE TITLE
Recent Episodes not loading properly

### ISSUE THREAD

**Issue by BRB1993** [patrickmaher/Enhanced-RT#10]
Ever since the last update (3 August, 2019, update 3.8.2) recent episodes do not load properly. The videos appear briefly before disappearing, leaving the loading icon constantly spinning. Reinstalling RT Enhanced doesn't do anything, nor does reinstalling Google Chrome.

**Comment by patrickmaher** [comment]
Do you have the Rooster Teeth++ extension created by @Noojuno installed? I just enabled it on my end and it seems to be causing the issue you described.

**Comment by patrickmaher** [comment]
I looked back and found the [Reddit post](https://www.reddit.com/r/roosterteeth/comments/8h6kr5/rooster_teeth_update_13_episode_sorting_link/dyiccii/) where @Noojuno and I resolved this in the past. Since Rooster Teeth Engineering changed video URLs from /episode to /watch last month it caused this issue to resurface.

**Comment by BRB1993** [comment]
Nope, I’ve only got the RT Enhanced extension installed.

**Comment by patrickmaher** [comment]
Could be something else interfering. Since you see the videos briefly it means that Enhanced RT is loading the video list but then something is deleting that part of the page. I need some more information so we can get this solved.

Are you using the Chrome extension or the Tampermonkey/Greasemonkey userscript?
Which browser are you using?
When you load the page, do you see any errors in your browsers developer console?
Do you get the same issue when you use Enhanced RT in a different browser?

**Comment by BRB1993** [comment]
I mucked around with some of the settings on Google Chrome and it seems to be working properly now. Must've been a glitch or something with Google Chrome itself.

**Comment by patrickmaher** [comment]
Glad that you got it resolved.
