### ISSUE TITLE
Recently Added - dead again (December 2019)

### ISSUE THREAD

**Issue by Countryen** [patrickmaher/Enhanced-RT#12]
Huhu, seems like "Recently Added" tab is dead again, see screenshot below. The same reason as always? Or maybe a CORS/CORB error with their api?

![image](https://user-images.githubusercontent.com/11256873/71365861-8c79a980-25a0-11ea-8de1-06e8ada3c5ab.png)

![image](https://user-images.githubusercontent.com/11256873/71365476-699ac580-259f-11ea-86b1-81843c2f8038.png)

Note: Sometimes, the icons to filter are displayed, sometimes only the "eye" is displayed.

See also: #8 

Merry Christmas and Happy Holidays - no need to hurry ;)

**Comment by patrickmaher** [comment]
Thanks for the report. I was looking into this over the weekend. It appears to be a CORS issue with accessing the API. I need to do some more reading and figure out if I can fix it on my end.

https://www.reddit.com/r/roosterteeth/comments/ebnke6/enhanced_rt_problems/fbltbvu/

edit to pull in my comment from the reddit post for sake of documentation:

> I took a look at the issue yesterday and the problem is more complicated than I expected. It looks like the problem is due to security changes in Chromium that block the extension from accessing the Rooster Teeth API. This would explain why the extension still works in Firefox but not in Chrome. This would also explain why the extension broke in different Chromium based browsers at different times
> 
> It appears that the extension is being blocked from CORS. Since the API is hosted on its own subdomain the extension is unable to access the API. Although it is confusing that the extension is still able to pull the channel data from the API. I need to do some research to figure out how to solve this issue. It may end up that Rooster Teeth Engineering needs to do something on their end to allow extensions to access the API properly. I wont know for sure until I look into it further. If anyone has any insights I would be interested to hear them.

**Comment by Countryen** [comment]
It is a CORS/CORB issue. I've managed to get it running again with a local copy, with changed code of course, see my fork/commit above for the changes if you are interested in the solution - ofc, this is only a poc and quick and dirty but shows how it can be done - no need for RT to change their API.

Chrome doesn't want you to fetch/XHR in the `user.js` anymore -> instead, they want you to use the `chrome.runtime.sendMessage(request,response)` system with a `background.js` page. Appearently, this resolves critical security issues with CORB/CORS (related to spectre I think).

Basically, my solution moved all `XmlHttpRequests` from the `user.js` and moved it to a new `background.js` using the mentioned `chrome.runtime.sendMessage`. Some changes needed to be done because inside the `background.js` you can't modify the DOM, so this still needs to happen in the user.js. Also, some "global objects" aren't available when using this technique (that's why, for example, I pass everything as arguments to `getEpisodes()`).

**Resources:**
- [See chapter 2 here, explaining what you should do for XHR](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches)
- [Chrome Docs about XHR](https://developer.chrome.com/extensions/xhr#xhr-vs-content-scripts)
- [Information about Background Scripts](https://developer.chrome.com/extensions/background_pages)
- [Youtube Video from the Chrome Developers about CORB and spectre and stuff](https://youtu.be/dBuykrdhK-A?t=1390)

I think until you changed your code, you can use some "allowlisting" or special properties to still allow it, but sooner than later you have to change it.

**Note:** It would be easier to generate an "request any URL" kind of handler, but the dev team advises against such a thing (security vulnerability), that's why every XmlHttpRequest is its own function..

**Note:** I've only really tested the "Recently Added" page (which works), not all of the other functionalities in this poc.

**Comment by patrickmaher** [comment]
Thank you! The information and code that you provided are a huge help.

I am still confused by the channel logos at the top of the Recently Added page. Most of the time the icons are loading. The [channel data](https://svod-be.roosterteeth.com/api/v1/channels) for the icons is coming from the API. How is the extension accessing the API if the extension does not have permission for CORS with svod-be.roosterteeth.com? If I refresh a few times the channel logos will disappear and then I can see a CORB error blocking access to the channel data. I can't figure out why it works sometimes but not always.

It appears that the new Chrome extension restrictions cause the content script to adhere to the same restrictions as the page it is running within. So, Enhanced RT should have access to everything that https://roosterteeth.com has access too.

I have done some testing and it appears that the API is responding with:
access-control-allow-origin: https://roosterteeth.com

This should allow Enhanced RT to access the API through CORS since the extension is running within https://roosterteeth.com. I believe that is why the channel data is loading from the API sometimes. I checked the headers returned by the API when a CORB error appears. In those cases access-control-allow-origin is null. At the moment I am trying to figure out why access-control-allow-origin is null. Figuring that out might solve the problem.

**Comment by patrickmaher** [comment]
I think I may have fixed it. I need to do more testing before I am sure. @Countryen, if it works, you are not going to believe how simple it was. I'll report back later today.

**Comment by patrickmaher** [comment]
@Countryen, while reviewing your changes to manifest.json I noticed that the matches field was set to "*://*.roosterteeth.com/*". This was a decision that I made when the Rooster Teeth site used different subdomains for each channel. Now the RT site is just https://roosterteeth.com. There is no http, there is no www, there are no subdomains for the main site. Every page on the main site is redirected to https://roosterteeth.com now. So, the matches field can now safely be changed to "https://roosterteeth.com/*". I should have changed this a long time ago but I was worried because Chrome gives scary warnings to the user when an extension changes its matches.

There are still subdomains but those are used for the API, watch time server, etc. I noticed an error in the Chrome developer console while hitting the [API file for channel data](https://svod-be.roosterteeth.com/api/v1/channels) directly. The wildcards in the matches field were causing the extension to run on the API files. So, when the extension used XHR to request the API files, a second instantiation of the extension was being run on the data returned from the API. That second instantiation was messing with the response data before the first instantiation could receive it (most of the time). That caused the response from the API to show a null access-control-allow-origin field when the response made its way back to the first instantiation. This bug has always been there but it just didn't matter until the new CORS restrictions.

It appears that the channel logos were loading most of the time only because the first instantiation of the extension was receiving the channel data before a second instantiation could be loaded. Possibly because the channel data is very small or because the browser is bogged down with rendering the page at that point.

Thanks again @Countryen. It would have taken me a lot longer to go through this without your help.

**Comment by Countryen** [comment]
Happy to help a bit :) 
Glad that you made progress / fixed the issue.

2 quotes from the [site above](https://www.chromium.org/Home/chromium-security/extension-content-script-fetches) for clarification:

> To mitigate these concerns, future versions of Chrome will limit content scripts to the same fetches that the page itself can perform.  Content scripts can instead ask their background pages to fetch data from other origins on their behalf, where the request can be made from an extension process rather than a more easily exploitable renderer process.

Above is probably related to what you found out why some things work still...

> Later in 2019, Extension Manifest V3 will become available, **requiring cross-origin requests to occur in background pages rather than content scripts**.  This new manifest version will have its own migration period, before support for Extension Manifest V2 is eventually removed from Chrome.

Because of this I think sooner-or-later they want you to discontinue XHR in frontend-scripts (they can be hijacked). 

Probably late 2020 as they currently have not decided yet, when to stop v2 support.
https://developer.chrome.com/extensions/migrating_to_manifest_v3

> We have not decided on a final end of life date for MV2.

---

But great if it works in the meantime again :) I really couldn't sleep well without this extension. Too bad it's not possible to "extend" their android app with this.

**Comment by patrickmaher** [comment]
If I understand correctly, the XHRs must be move to background.js only if it is not allowed by CORS. Since Rooster Teeth has set CORS to allow https://roosterteeth.com to access the API the extension should still be allowed to use XHR to access the API. The explanation on the Chromium site is a bit confusing. The [manifest v3 documentation](https://developer.chrome.com/extensions/migrating_to_manifest_v3#cors_changes) is a bit more concise.

I will wait and see what happens. At least we have your research and POC to refer back to if it becomes an issue in the future.
