### ISSUE TITLE
Way to contribute or donate?

### ISSUE THREAD

**Issue by Countryen** [patrickmaher/Enhanced-RT#5]
Hey I love this extension so I thought about donating or contributing.
Any way I can give something back for using this extension almost all the time?

Awesome:
- Open Source (here on GitHub)
- Reliable and constantly updated
- KISS / JAGNI like
- Free and Chrome

Also the new icons look really nice.
This extension is just exactly what I need for my RT watching schedule.

I could also provide coding to assist/contribute - maybe refactoring or smth. if you have anything in mind.

**Comment by Countryen** [comment]
Hey @patrickmaher, still no update on this "issue"? ;) Would like to send you at least a coffee or something as I still really love the extension/script and - when working again ;) - use it every single day. Found no way to donate on github/chromeextension, yet. Christmas beeing the time of giving and all...

**Comment by patrickmaher** [comment]
Sorry that I didn't reply sooner. I primarily made this extension for my own use. I decided to release it publicly because I saw many people in the community that were frustrated with the RT website. I still consider it a project created for my own use and for the fun of adding new features.

I don't want to accept donations. I don't want to setup any expectations or feel that I need to work on it at times when I can't or don't want to. I want the project to remain something fun and interesting to work on. It has been great to hear from other people in the community that enjoy using Enhanced RT. That alone was worth the effort of releasing it publicly and maintaining it.

It has been a long time since I last worked on Enhanced RT. I have some other projects I am working on which are taking a lot of my attention. I stopped watching RT content about a year ago but I check in once in awhile to make sure the extension is still working. I don't expect to add any new features anytime soon but I will continue to fix the extension if the Recently Added page breaks.

I welcome anyone that would like to contribute fixes or new features to the project. If someone wants to fork it and release their own new and improved version that would also be cool.

Thanks again for your kind words @Countryen.
